apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-access-role
  namespace: default
rules:
  - apiGroups: ["apps", "batch", "extensions"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot-duckdns
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certbot-duckdns-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access-role
subjects:
  - kind: ServiceAccount
    name: certbot-duckdns
    namespace: default
